-- This file was generated automatically with a tool.
goods = {}
goods["Acid"] = {name="Acid", plural="Acid", description="A tank filled with vitriolic acid.", icon="data/textures/icons/acid.png", mesh="data/meshes/trading-goods/acid.obj", price=402, size=1, level=3, importance=2, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true}, }
goods["Acron Drug"] = {name="Acron Drug", plural="Acron Drugs", description="A highly addictive drug.", icon="data/textures/icons/powder.png", mesh="data/meshes/trading-goods/crate-food.obj", price=6000, size=0.1, level=nil, importance=0, illegal=true, dangerous=false, tags={consumer=true}, chains={}, }
goods["Adhesive"] = {name="Adhesive", plural="Adhesive", description="Common adhesive. Used on smaller parts where there's no space for screws.", icon="data/textures/icons/adhesive.png", mesh="data/meshes/trading-goods/adhesive-solvent.obj", price=402, size=0.25, level=3, importance=3, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true,technology=true}, }
goods["Aluminum"] = {name="Aluminum", plural="Aluminum", description="A container full of pure aluminum.", icon="data/textures/icons/aluminium.png", mesh="data/meshes/trading-goods/crate-07.obj", price=200, size=1, level=0, importance=7, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Ammunition"] = {name="Ammunition", plural="Ammunition", description="Ammunition for projectile weapons.", icon="data/textures/icons/ammo-box.png", mesh="data/meshes/trading-goods/crate-01.obj", price=3786, size=3, level=5, importance=1, illegal=false, dangerous=false, tags={military=true}, chains={military=true}, }
goods["Ammunition L"] = {name="Ammunition L", plural="Ammunition L", description="Ammunition for turrets.", icon="data/textures/icons/ammunition-l.png", mesh="data/meshes/trading-goods/crate-01.obj", price=422, size=2.5, level=4, importance=0, illegal=false, dangerous=false, tags={military=true}, chains={military=true}, }
goods["Ammunition M"] = {name="Ammunition M", plural="Ammunition M", description="Ammunition for large handheld guns.", icon="data/textures/icons/ammunition-m.png", mesh="data/meshes/trading-goods/crate-01.obj", price=422, size=1.5, level=4, importance=0, illegal=false, dangerous=false, tags={military=true}, chains={military=true}, }
goods["Ammunition S"] = {name="Ammunition S", plural="Ammunition S", description="Ammunition for small handguns.", icon="data/textures/icons/ammunition-s.png", mesh="data/meshes/trading-goods/crate-01.obj", price=422, size=0.5, level=4, importance=0, illegal=false, dangerous=false, tags={military=true}, chains={military=true}, }
goods["Antigrav Generator"] = {name="Antigrav Generator", plural="Antigrav Generators", description="A generator that creates a field where gravity has no effect.", icon="data/textures/icons/anti-grav-generator.png", mesh="data/meshes/trading-goods/generator.obj", price=71632, size=2.5, level=8, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Antigrav Unit"] = {name="Antigrav Unit", plural="Antigrav Units", description="This device generates antigrav fields for easier transportation of objects.", icon="data/textures/icons/antigrav-unit.png", mesh="data/meshes/trading-goods/crate-03.obj", price=25391, size=2.5, level=7, importance=4, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Avorion Ore"] = {name="Avorion Ore", plural="Avorion Ore", description="Avorion ore that can be refined into Avorion.", icon="data/textures/icons/rock.png", mesh="", price=12, size=0.025, level=nil, importance=0, illegal=false, dangerous=false, tags={avorion=true,basic=true,ore=true}, chains={}, }
goods["Beer"] = {name="Beer", plural="Beer", description="A box of beer.", icon="data/textures/icons/beer-stein.png", mesh="data/meshes/trading-goods/crate-food.obj", price=216, size=0.5, level=4, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Bio Gas"] = {name="Bio Gas", plural="Bio Gas", description="Biological gas. Probably toxic.", icon="data/textures/icons/bio-gas.png", mesh="data/meshes/trading-goods/crate-gas.obj", price=213, size=1, level=2, importance=3, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Body Armor"] = {name="Body Armor", plural="Body Armors", description="Exoskeleton armor for elite soldiers.", icon="data/textures/icons/kevlar-vest.png", mesh="data/meshes/trading-goods/crate-01.obj", price=95906, size=1.5, level=9, importance=0, illegal=false, dangerous=false, tags={military=true}, chains={military=true}, }
goods["Book"] = {name="Book", plural="Books", description="A book with an exciting, procedurally generated story.", icon="data/textures/icons/open-book.png", mesh="data/meshes/trading-goods/crate-05.obj", price=319, size=0.2, level=3, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Carbon"] = {name="Carbon", plural="Carbon", description="A container of carbon.", icon="data/textures/icons/carbon.png", mesh="data/meshes/trading-goods/crate-07.obj", price=423, size=1, level=2, importance=5, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Cattle"] = {name="Cattle", plural="Cattle", description="Cattle.", icon="data/textures/icons/cattle.png", mesh="data/meshes/trading-goods/crate-food.obj", price=254, size=1.5, level=2, importance=2, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Chemicals"] = {name="Chemicals", plural="Chemicals", description="Multitank containing all sorts of different chemicals, most of them toxic.", icon="data/textures/icons/chemical.png", mesh="data/meshes/trading-goods/crate-07.obj", price=402, size=1, level=3, importance=6, illegal=false, dangerous=false, tags={industrial=true}, chains={consumer=true,industrial=true,military=true,technology=true}, }
goods["Chlorine"] = {name="Chlorine", plural="Chlorine", description="A pressure container filled with pure chlorine.", icon="data/textures/icons/chlorine.png", mesh="data/meshes/trading-goods/crate-gas.obj", price=150, size=1, level=0, importance=1, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Clothes"] = {name="Clothes", plural="Clothes", description="Normal looking clothing.", icon="data/textures/icons/trousers.png", mesh="data/meshes/trading-goods/crate-05.obj", price=102, size=1, level=4, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Coal"] = {name="Coal", plural="Coal", description="Fossil fuel. Still used in some factories.", icon="data/textures/icons/fossil-fuel.png", mesh="", price=200, size=2, level=0, importance=2, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Cocoa"] = {name="Cocoa", plural="Cocoa", description="A bag of roasted cocoa beans.", icon="data/textures/icons/cocoa.png", mesh="data/meshes/trading-goods/crate-08.obj", price=87, size=0.2, level=5, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Coffee"] = {name="Coffee", plural="Coffee", description="A bag of roasted coffee beans.", icon="data/textures/icons/coffee-beans.png", mesh="data/meshes/trading-goods/crate-08.obj", price=187, size=0.2, level=5, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Computation Mainframe"] = {name="Computation Mainframe", plural="Computation Mainframes", description="A high speed computer used as infrastructure for stations and ships.", icon="data/textures/icons/computation-mainframe.png", mesh="data/meshes/trading-goods/crate-01.obj", price=37940, size=1, level=7, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Conductor"] = {name="Conductor", plural="Conductors", description="Thick cables used for transmitting electrical energy.", icon="data/textures/icons/conductor.png", mesh="data/meshes/trading-goods/crate-04.obj", price=168, size=0.15, level=4, importance=9, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Coolant"] = {name="Coolant", plural="Coolant", description="A canister full of coolant for the most common engines.", icon="data/textures/icons/snowflake-2.png", mesh="data/meshes/trading-goods/crate-liquids.obj", price=402, size=0.5, level=3, importance=4, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true,technology=true}, }
goods["Copper"] = {name="Copper", plural="Copper", description="A medium sized crate full of copper bars.", icon="data/textures/icons/copper.png", mesh="", price=350, size=1, level=0, importance=5, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Corn"] = {name="Corn", plural="Corn", description="A container full of corn.", icon="data/textures/icons/corn.png", mesh="data/meshes/trading-goods/crate-09.obj", price=28, size=1, level=1, importance=5, illegal=false, dangerous=false, tags={consumer=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Crystal"] = {name="Crystal", plural="Crystals", description="Naturally grown crystals.", icon="data/textures/icons/crystal.png", mesh="data/meshes/trading-goods/crystal.obj", price=190, size=1.5, level=0, importance=2, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Dairy"] = {name="Dairy", plural="Dairy", description="A tank full of dairy products, like yoghurt or butter.", icon="data/textures/icons/udder.png", mesh="data/meshes/trading-goods/crate-liquids.obj", price=19, size=1, level=3, importance=1, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Diamond"] = {name="Diamond", plural="Diamonds", description="A handful of diamonds. Useless unless you know where to sell them.", icon="data/textures/icons/diamond.png", mesh="data/meshes/trading-goods/diamond.obj", price=750, size=0.05, level=0, importance=3, illegal=false, dangerous=false, tags={basic=true}, chains={consumer=true,industrial=true,technology=true}, }
goods["Display"] = {name="Display", plural="Displays", description="A touch display for computers.", icon="data/textures/icons/checkbox-tree.png", mesh="data/meshes/trading-goods/display.obj", price=7858, size=1, level=6, importance=5, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Drill"] = {name="Drill", plural="Drills", description="Mining drill, often used in asteroid mines.", icon="data/textures/icons/drill.png", mesh="data/meshes/trading-goods/crate-01.obj", price=20443, size=20, level=7, importance=1, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,technology=true}, }
goods["Drone"] = {name="Drone", plural="Drones", description="Unmanned little ships for everyday purposes.", icon="data/textures/icons/spoutnik.png", mesh="data/meshes/trading-goods/satellite.obj", price=7754, size=10, level=5, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Electro Magnet"] = {name="Electro Magnet", plural="Electro Magnets", description="High power multi-purpose electromagnets.", icon="data/textures/icons/electro-magnet.png", mesh="data/meshes/trading-goods/crate-04.obj", price=483, size=0.75, level=5, importance=4, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Electromagnetic Charge"] = {name="Electromagnetic Charge", plural="Electromagnetic Charges", description="One-time use charge that can set free a strong electromagnetic pulse.", icon="data/textures/icons/electromagnetic-charge.png", mesh="data/meshes/trading-goods/crate-06.obj", price=13985, size=1, level=6, importance=0, illegal=false, dangerous=false, tags={military=true}, chains={military=true}, }
goods["Electron Accelerator"] = {name="Electron Accelerator", plural="Electron Accelerators", description="A device that accelerates electrons to near light speed.", icon="data/textures/icons/electron-accelerator.png", mesh="data/meshes/trading-goods/accelerator.obj", price=125431, size=12, level=8, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Energy Cell"] = {name="Energy Cell", plural="Energy Cells", description="Small blue canisters with a high voltage charge inside them.", icon="data/textures/icons/battery-pack-alt.png", mesh="data/meshes/trading-goods/energy-cell.obj", price=50, size=1, level=0, importance=43, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Energy Container"] = {name="Energy Container", plural="Energy Containers", description="Bigger than energy cells, these devices can hold up to 1000x more energy.", icon="data/textures/icons/electric.png", mesh="data/meshes/trading-goods/generator.obj", price=1087, size=4.5, level=5, importance=2, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Energy Generator"] = {name="Energy Generator", plural="Energy Generators", description="A device that generates energy from an antimatter core.", icon="data/textures/icons/energy-generator.png", mesh="data/meshes/trading-goods/generator.obj", price=15957, size=2, level=6, importance=3, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,technology=true}, }
goods["Energy Inverter"] = {name="Energy Inverter", plural="Energy Inverters", description="Converts electron flow into positron flow.", icon="data/textures/icons/energy-inverter.png", mesh="data/meshes/trading-goods/crate-04.obj", price=1277, size=3, level=6, importance=0, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,technology=true}, }
goods["Energy Tube"] = {name="Energy Tube", plural="Energy Tubes", description="Long tubes that are used to transport high amounts of energy.", icon="data/textures/icons/energy-tube.png", mesh="data/meshes/trading-goods/steel-tube.obj", price=2895, size=1.5, level=5, importance=7, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Explosive Charge"] = {name="Explosive Charge", plural="Explosive Charges", description="A military grade explosive.", icon="data/textures/icons/explosive-charge.png", mesh="data/meshes/trading-goods/crate-06.obj", price=1423, size=1.5, level=4, importance=0, illegal=false, dangerous=true, tags={military=true}, chains={military=true}, }
goods["Fabric"] = {name="Fabric", plural="Fabric", description="Raw fabric used for clothing or bandages.", icon="data/textures/icons/fabric.png", mesh="data/meshes/trading-goods/crate-food.obj", price=91, size=1, level=3, importance=2, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true,technology=true}, }
goods["Fertilizer"] = {name="Fertilizer", plural="Fertilizer", description="A tank with fertilizer, important for more exotic plants.", icon="data/textures/icons/fertilizer.png", mesh="data/meshes/trading-goods/crate-07.obj", price=319, size=1, level=1, importance=3, illegal=false, dangerous=false, tags={industrial=true}, chains={consumer=true,industrial=true}, }
goods["Fish"] = {name="Fish", plural="Fish", description="A barrel full of fish.", icon="data/textures/icons/fish.png", mesh="data/meshes/trading-goods/crate-food.obj", price=152, size=0.5, level=2, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Fluorine"] = {name="Fluorine", plural="Fluorine", description="A pressure container filled with pure fluorine.", icon="data/textures/icons/fluorine.png", mesh="data/meshes/trading-goods/crate-gas.obj", price=250, size=1, level=0, importance=2, illegal=false, dangerous=true, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Food"] = {name="Food", plural="Food", description="Healthy food packaged in one-man portions.", icon="data/textures/icons/chicken-leg.png", mesh="data/meshes/trading-goods/crate-food.obj", price=300, size=0.5, level=4, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Food Bar"] = {name="Food Bar", plural="Food Bars", description="Bars of compressed food.", icon="data/textures/icons/bar.png", mesh="", price=223, size=0.5, level=2, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Force Generator"] = {name="Force Generator", plural="Force Generators", description="A generator that creates a force field that pushes or pulls objects.", icon="data/textures/icons/force-generator.png", mesh="data/meshes/trading-goods/generator.obj", price=49576, size=4, level=7, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Fruit"] = {name="Fruit", plural="Fruits", description="A specially engineered fruit, containing a wide range of important vitamins.", icon="data/textures/icons/shiny-apple.png", mesh="data/meshes/trading-goods/crate-09.obj", price=56, size=0.5, level=1, importance=2, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Fuel"] = {name="Fuel", plural="Fuel", description="A tank with fuel for vehicles or space ships.", icon="data/textures/icons/fuel.png", mesh="data/meshes/trading-goods/crate-liquids.obj", price=1232, size=1, level=2, importance=2, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true,technology=true}, }
goods["Fungus"] = {name="Fungus", plural="Fungi", description="A container with fungus, used for making alcohol.", icon="data/textures/icons/mushroom.png", mesh="data/meshes/trading-goods/crate-food.obj", price=46, size=1, level=3, importance=2, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Fusion Core"] = {name="Fusion Core", plural="Fusion Cores", description="Highly advanced portable fusion generator.", icon="data/textures/icons/fusion-core.png", mesh="data/meshes/trading-goods/crate-03.obj", price=5114, size=2.5, level=6, importance=2, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Fusion Generator"] = {name="Fusion Generator", plural="Fusion Generators", description="The bigger, better and more advanced variant of the fusion core.", icon="data/textures/icons/fusion-generator.png", mesh="data/meshes/trading-goods/generator.obj", price=39553, size=2.5, level=7, importance=1, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Gauss Rail"] = {name="Gauss Rail", plural="Gauss Rail", description="A rail for immense acceleration of projectiles with magnetic fields.", icon="data/textures/icons/gauss-rail.png", mesh="data/meshes/trading-goods/crate-06.obj", price=7735, size=2, level=6, importance=1, illegal=false, dangerous=false, tags={military=true}, chains={military=true,technology=true}, }
goods["Gem"] = {name="Gem", plural="Gems", description="A big gem. It's worth a lot, but you have to sell it first.", icon="data/textures/icons/saphir.png", mesh="data/meshes/trading-goods/gem.obj", price=400, size=0.05, level=0, importance=1, illegal=false, dangerous=false, tags={basic=true}, chains={consumer=true}, }
goods["Glass"] = {name="Glass", plural="Glass", description="A box containing several plates of glass.", icon="data/textures/icons/metal-disc.png", mesh="data/meshes/trading-goods/crate-07.obj", price=182, size=1, level=1, importance=3, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true,technology=true}, }
goods["Gold"] = {name="Gold", plural="Gold", description="A small box containing gold bars.", icon="data/textures/icons/metal-bar.png", mesh="", price=600, size=0.5, level=0, importance=8, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Gun"] = {name="Gun", plural="Guns", description="Hand guns. Used by robots and living beings.", icon="data/textures/icons/bolter-gun.png", mesh="data/meshes/trading-goods/crate-tools.obj", price=1232, size=0.5, level=6, importance=1, illegal=false, dangerous=true, tags={military=true}, chains={military=true}, }
goods["Helium"] = {name="Helium", plural="Helium", description="A pressure container filled with pure helium gas.", icon="data/textures/icons/helium.png", mesh="data/meshes/trading-goods/crate-gas.obj", price=50, size=1, level=0, importance=1, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["High Capacity Lens"] = {name="High Capacity Lens", plural="High Capacity Lenses", description="A focal lens designed for high capacity lasers.", icon="data/textures/icons/high-capacity-lens.png", mesh="data/meshes/trading-goods/crate-06.obj", price=4689, size=1, level=3, importance=0, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,technology=true}, }
goods["High Pressure Tube"] = {name="High Pressure Tube", plural="High Pressure Tubes", description="Tubes that can sustain extremely high pressure. Most commonly used in factories or weapons.", icon="data/textures/icons/high-pressure-tube.png", mesh="data/meshes/trading-goods/steel-tube.obj", price=1650, size=2, level=5, importance=2, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Hydrogen"] = {name="Hydrogen", plural="Hydrogen", description="A pressure container filled with pure hydrogen.", icon="data/textures/icons/hydrogen.png", mesh="data/meshes/trading-goods/crate-gas.obj", price=150, size=1, level=0, importance=2, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Industrial Tesla Coil"] = {name="Industrial Tesla Coil", plural="Industrial Tesla Coils", description="Tesla coil used for melting of metals in factories.", icon="data/textures/icons/industrial-tesla-coil.png", mesh="data/meshes/trading-goods/tesla-coil.obj", price=10314, size=5.5, level=7, importance=0, illegal=false, dangerous=true, tags={industrial=true,technology=true}, chains={industrial=true,technology=true}, }
goods["Iron Ore"] = {name="Iron Ore", plural="Iron Ore", description="Iron ore that can be refined into Iron.", icon="data/textures/icons/rock.png", mesh="", price=2, size=0.025, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,iron=true,ore=true}, chains={}, }
goods["Jewelry"] = {name="Jewelry", plural="Jewelry", description="Beautiful and very expensive jewelry.", icon="data/textures/icons/gem-chain.png", mesh="data/meshes/trading-goods/crate-05.obj", price=1260, size=0.2, level=1, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Laser Compressor"] = {name="Laser Compressor", plural="Laser Compressors", description="A device that can bundle energy and emit a laser beam.", icon="data/textures/icons/laser-compressor.png", mesh="data/meshes/trading-goods/crate-03.obj", price=6577, size=1.5, level=6, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Laser Head"] = {name="Laser Head", plural="Laser Heads", description="A device used to focus laser beams.", icon="data/textures/icons/laser-head.png", mesh="data/meshes/trading-goods/crate-03.obj", price=4690, size=2, level=5, importance=1, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,technology=true}, }
goods["Laser Modulator"] = {name="Laser Modulator", plural="Laser Modulators", description="A device that changes various properties of lasers beams passing through it.", icon="data/textures/icons/laser-modulator.png", mesh="data/meshes/trading-goods/crate-01.obj", price=16742, size=3, level=6, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Lead"] = {name="Lead", plural="Lead", description="A medium sized crate filled with lead bars.", icon="data/textures/icons/lead.png", mesh="data/meshes/trading-goods/crate-07.obj", price=200, size=1, level=0, importance=1, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Leather"] = {name="Leather", plural="Leather", description="Treated leather, made from various animal hides.", icon="data/textures/icons/animal-hide.png", mesh="data/meshes/trading-goods/crate-food.obj", price=37, size=0.5, level=3, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Liquor"] = {name="Liquor", plural="Liquor", description="A box of high quality liquor.", icon="data/textures/icons/martini.png", mesh="data/meshes/trading-goods/crate-food.obj", price=1867, size=1.25, level=2, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Luxury Food"] = {name="Luxury Food", plural="Luxury Food", description="Luxurious food, made for the rich only.", icon="data/textures/icons/luxury-food.png", mesh="data/meshes/trading-goods/crate-food.obj", price=6452, size=2.5, level=6, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Meat"] = {name="Meat", plural="Meat", description="A box full of fresh meat.", icon="data/textures/icons/meat.png", mesh="data/meshes/trading-goods/crate-food.obj", price=37, size=0.5, level=3, importance=2, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Medical Supplies"] = {name="Medical Supplies", plural="Medical Supplies", description="A box with everyday medical supplies containing bandages, antibiotics and germicides.", icon="data/textures/icons/medical-supplies.png", mesh="data/meshes/trading-goods/medical-supplies.obj", price=3006, size=1, level=4, importance=0, illegal=false, dangerous=false, tags={consumer=true,technology=true}, chains={consumer=true,technology=true}, }
goods["Metal Plate"] = {name="Metal Plate", plural="Metal Plates", description="Big metal plates used for building platings of vehicles or ships.", icon="data/textures/icons/metal-scales.png", mesh="data/meshes/trading-goods/metal-plate.obj", price=792, size=3, level=4, importance=5, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true,technology=true}, }
goods["Microchip"] = {name="Microchip", plural="Microchips", description="Microchips are the most basic parts of computers.", icon="data/textures/icons/microchip.png", mesh="data/meshes/trading-goods/crate-06.obj", price=896, size=0.1, level=5, importance=7, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Military Tesla Coil"] = {name="Military Tesla Coil", plural="Military Tesla Coils", description="A repurposed tesla coil that can shoot directed high-intensity beams of electricity.", icon="data/textures/icons/industrial-tesla-coil.png", mesh="data/meshes/trading-goods/tesla-coil.obj", price=10314, size=4.5, level=7, importance=0, illegal=false, dangerous=true, tags={military=true}, chains={military=true}, }
goods["Mineral"] = {name="Mineral", plural="Minerals", description="A canister full of mineral powder.", icon="data/textures/icons/spices.png", mesh="data/meshes/trading-goods/crystal.obj", price=500, size=1.5, level=0, importance=3, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Mining Robot"] = {name="Mining Robot", plural="Mining Robots", description="A big robot used for mining in asteroid shafts where human beings would not survive.", icon="data/textures/icons/robot-golem.png", mesh="data/meshes/trading-goods/crate-01.obj", price=145977, size=8, level=9, importance=0, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,technology=true}, }
goods["Morn Drug"] = {name="Morn Drug", plural="Morn Drugs", description="An addictive drug that gives the user strong hallucinations.", icon="data/textures/icons/powder.png", mesh="data/meshes/trading-goods/crate-food.obj", price=5000, size=0.1, level=nil, importance=0, illegal=true, dangerous=false, tags={consumer=true}, chains={}, }
goods["Nanobot"] = {name="Nanobot", plural="Nanobots", description="Tiny robots that are able to get into almost everything.", icon="data/textures/icons/nanobots.png", mesh="data/meshes/trading-goods/crate-03.obj", price=1338, size=0.5, level=5, importance=4, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Naonite Ore"] = {name="Naonite Ore", plural="Naonite Ore", description="Naonite ore that can be refined into Naonite.", icon="data/textures/icons/rock.png", mesh="", price=4, size=0.025, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,naonite=true,ore=true}, chains={}, }
goods["Neon"] = {name="Neon", plural="Neon", description="A pressure container filled with pure neon.", icon="data/textures/icons/neon.png", mesh="data/meshes/trading-goods/crate-gas.obj", price=200, size=1, level=0, importance=2, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Neutron Accelerator"] = {name="Neutron Accelerator", plural="Neutron Accelerators", description="A device that accelerates neutrons to near light speed.", icon="data/textures/icons/neutron-accelerator.png", mesh="data/meshes/trading-goods/accelerator.obj", price=125431, size=15, level=8, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Nitrogen"] = {name="Nitrogen", plural="Nitrogen", description="A pressure container filled with pure nitrogen.", icon="data/textures/icons/nitrogen.png", mesh="data/meshes/trading-goods/crate-gas.obj", price=40, size=1, level=0, importance=2, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Ogonite Ore"] = {name="Ogonite Ore", plural="Ogonite Ore", description="Ogonite ore that can be refined into Ogonite.", icon="data/textures/icons/rock.png", mesh="", price=9, size=0.025, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,ogonite=true,ore=true}, chains={}, }
goods["Oil"] = {name="Oil", plural="Oil", description="A barrel of refined oil.", icon="data/textures/icons/oil-drum.png", mesh="data/meshes/trading-goods/crate-liquids.obj", price=490, size=1, level=1, importance=4, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true,technology=true}, }
goods["Ore"] = {name="Ore", plural="Ore", description="Raw ore containing some kind of metal.", icon="data/textures/icons/rock.png", mesh="", price=70, size=2, level=0, importance=2, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Oxygen"] = {name="Oxygen", plural="Oxygen", description="A pressure container filled with pure oxygen.", icon="data/textures/icons/oxygen.png", mesh="data/meshes/trading-goods/crate-gas.obj", price=80, size=1, level=0, importance=6, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Paint"] = {name="Paint", plural="Paint", description="A container full of paint.", icon="data/textures/icons/paint.png", mesh="data/meshes/trading-goods/crate-liquids.obj", price=481, size=1, level=4, importance=1, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true}, }
goods["Paper"] = {name="Paper", plural="Paper", description="A big stash of paper.", icon="data/textures/icons/papers.png", mesh="data/meshes/trading-goods/crate-05.obj", price=46, size=1, level=2, importance=1, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Plankton"] = {name="Plankton", plural="Plankton", description="A tank full of live plankton.", icon="data/textures/icons/turtle-shell.png", mesh="data/meshes/trading-goods/crate-09.obj", price=50, size=1, level=0, importance=1, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true,industrial=true}, }
goods["Plant"] = {name="Plant", plural="Plants", description="A container with soil and a wide range of green plants.", icon="data/textures/icons/plant.png", mesh="data/meshes/trading-goods/crate-09.obj", price=14, size=1.5, level=1, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Plasma Cell"] = {name="Plasma Cell", plural="Plasma Cells", description="A battery that can emit a short but strong pulse of energy.", icon="data/textures/icons/plasma-cell.png", mesh="data/meshes/trading-goods/plasma-cell.obj", price=174, size=0.25, level=4, importance=8, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Plastic"] = {name="Plastic", plural="Plastic", description="A container with plastic. This is melted when used.", icon="data/textures/icons/cargo-hold.png", mesh="data/meshes/trading-goods/crate-07.obj", price=137, size=0.5, level=2, importance=9, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true,technology=true}, }
goods["Platinum"] = {name="Platinum", plural="Platinum", description="A small box containing platinum bars.", icon="data/textures/icons/metal-bar.png", mesh="", price=750, size=0.5, level=0, importance=7, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Potato"] = {name="Potato", plural="Potatoes", description="A container full of potatoes.", icon="data/textures/icons/potato.png", mesh="data/meshes/trading-goods/crate-09.obj", price=24, size=1, level=1, importance=1, illegal=false, dangerous=false, tags={consumer=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Power Unit"] = {name="Power Unit", plural="Power Units", description="A big device that can create a huge amount of energy over a long period of time.", icon="data/textures/icons/power-unit.png", mesh="data/meshes/trading-goods/generator.obj", price=1211, size=5, level=5, importance=8, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Processor"] = {name="Processor", plural="Processors", description="The heart of a computer or any device that does some kind of calculation.", icon="data/textures/icons/processor.png", mesh="data/meshes/trading-goods/crate-03.obj", price=7858, size=0.1, level=6, importance=8, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Protein"] = {name="Protein", plural="Protein", description="Protein for quickly restoring one's energy.", icon="data/textures/icons/bar.png", mesh="", price=34, size=0.1, level=4, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Proton Accelerator"] = {name="Proton Accelerator", plural="Proton Accelerators", description="A device that accelerates protons to near light speed.", icon="data/textures/icons/proton-accelerator.png", mesh="data/meshes/trading-goods/accelerator.obj", price=125431, size=15, level=8, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Raw Oil"] = {name="Raw Oil", plural="Raw Oil", description="A barrel of unrefined oil.", icon="data/textures/icons/oil-drum.png", mesh="data/meshes/trading-goods/crate-07.obj", price=150, size=1, level=0, importance=1, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Rice"] = {name="Rice", plural="Rice", description="A container full of rice.", icon="data/textures/icons/powder.png", mesh="data/meshes/trading-goods/crate-09.obj", price=15, size=1, level=1, importance=2, illegal=false, dangerous=false, tags={consumer=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Rift Avorion Ore"] = {name="Rift Avorion Ore", plural="Rift Avorion Ore", description="Very rich Avorion ore that can only be found in rifts. Can be refined into Avorion. Yields 4x as much as normal Avorion Ore.", icon="data/textures/icons/rift-rock.png", mesh="", price=12, size=0.05, level=nil, importance=0, illegal=false, dangerous=false, tags={avorion=true,basic=true,ore=true,rich=true,rift=true}, chains={}, }
goods["Rift Iron Ore"] = {name="Rift Iron Ore", plural="Rift Iron Ore", description="Very rich Iron ore that can only be found in rifts. Can be refined into Iron. Yields 4x as much as normal Iron Ore.", icon="data/textures/icons/rift-rock.png", mesh="", price=2, size=0.05, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,iron=true,ore=true,rich=true,rift=true}, chains={}, }
goods["Rift Naonite Ore"] = {name="Rift Naonite Ore", plural="Rift Naonite Ore", description="Very rich Naonite ore that can only be found in rifts. Can be refined into Naonite. Yields 4x as much as normal Naonite Ore.", icon="data/textures/icons/rift-rock.png", mesh="", price=4, size=0.05, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,naonite=true,ore=true,rich=true,rift=true}, chains={}, }
goods["Rift Ogonite Ore"] = {name="Rift Ogonite Ore", plural="Rift Ogonite Ore", description="Very rich Ogonite ore that can only be found in rifts. Can be refined into Ogonite. Yields 4x as much as normal Ogonite Ore.", icon="data/textures/icons/rift-rock.png", mesh="", price=9, size=0.05, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,ogonite=true,ore=true,rich=true,rift=true}, chains={}, }
goods["Rift Research Data"] = {name="Rift Research Data", plural="Rift Research Data", description="A memory device with valuable research data about subspace rifts. Can be traded for equipment or sold for money at a Rift Research Center.", icon="data/textures/icons/info-chip.png", mesh="data/meshes/trading-goods/crate-food.obj", price=5000, size=0.5, level=nil, importance=0, illegal=false, dangerous=false, tags={mission_relevant=true,rare=true,technology=true}, chains={}, }
goods["Rift Titanium Ore"] = {name="Rift Titanium Ore", plural="Rift Titanium Ore", description="Very rich Titanium ore that can only be found in rifts. Can be refined into Titanium. Yields 4x as much as normal Titanium Ore.", icon="data/textures/icons/rift-rock.png", mesh="", price=3, size=0.05, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,ore=true,rich=true,rift=true,titanium=true}, chains={}, }
goods["Rift Trinium Ore"] = {name="Rift Trinium Ore", plural="Rift Trinium Ore", description="Very rich Trinium ore that can only be found in rifts. Can be refined into Trinium. Yields 4x as much as normal Trinium Ore.", icon="data/textures/icons/rift-rock.png", mesh="", price=5, size=0.05, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,ore=true,rich=true,rift=true,trinium=true}, chains={}, }
goods["Rift Xanion Ore"] = {name="Rift Xanion Ore", plural="Rift Xanion Ore", description="Very rich Xanion ore that can only be found in rifts. Can be refined into Xanion. Yields 4x as much as normal Xanion Ore.", icon="data/textures/icons/rift-rock.png", mesh="", price=7, size=0.05, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,ore=true,rich=true,rift=true,xanion=true}, chains={}, }
goods["Rocket"] = {name="Rocket", plural="Rockets", description="Ammunition for rocket launchers.", icon="data/textures/icons/rocket.png", mesh="data/meshes/trading-goods/crate-01.obj", price=11250, size=4, level=6, importance=0, illegal=false, dangerous=true, tags={military=true}, chains={military=true}, }
goods["Rubber"] = {name="Rubber", plural="Rubber", description="A bouncing block of rubber.", icon="data/textures/icons/cubes.png", mesh="data/meshes/trading-goods/crate-07.obj", price=686, size=1, level=2, importance=1, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true}, }
goods["Satellite"] = {name="Satellite", plural="Satellites", description="A satellite used for research or spying.", icon="data/textures/icons/satellite.png", mesh="data/meshes/trading-goods/satellite.obj", price=65714, size=15, level=7, importance=0, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Scrap Avorion"] = {name="Scrap Avorion", plural="Scrap Avorion", description="Scrap Avorion that can be refined into Avorion.", icon="data/textures/icons/scrap-metal.png", mesh="", price=24, size=0.04, level=nil, importance=0, illegal=false, dangerous=false, tags={avorion=true,basic=true,scrap=true}, chains={}, }
goods["Scrap Iron"] = {name="Scrap Iron", plural="Scrap Iron", description="Scrap Iron that can be refined into Iron.", icon="data/textures/icons/scrap-metal.png", mesh="", price=4, size=0.04, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,iron=true,scrap=true}, chains={}, }
goods["Scrap Metal"] = {name="Scrap Metal", plural="Scrap Metal", description="A container full of metal junk.", icon="data/textures/icons/scrap-metal.png", mesh="", price=25, size=3, level=0, importance=1, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Scrap Naonite"] = {name="Scrap Naonite", plural="Scrap Naonite", description="Scrap Naonite that can be refined into Naonite.", icon="data/textures/icons/scrap-metal.png", mesh="", price=7, size=0.04, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,naonite=true,scrap=true}, chains={}, }
goods["Scrap Ogonite"] = {name="Scrap Ogonite", plural="Scrap Ogonite", description="Scrap Ogonite that can be refined into Ogonite.", icon="data/textures/icons/scrap-metal.png", mesh="", price=18, size=0.04, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,ogonite=true,scrap=true}, chains={}, }
goods["Scrap Titanium"] = {name="Scrap Titanium", plural="Scrap Titanium", description="Scrap Titanium that can be refined into Titanium.", icon="data/textures/icons/scrap-metal.png", mesh="", price=5, size=0.04, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,scrap=true,titanium=true}, chains={}, }
goods["Scrap Trinium"] = {name="Scrap Trinium", plural="Scrap Trinium", description="Scrap Trinium that can be refined into Trinium.", icon="data/textures/icons/scrap-metal.png", mesh="", price=10, size=0.04, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,scrap=true,trinium=true}, chains={}, }
goods["Scrap Xanion"] = {name="Scrap Xanion", plural="Scrap Xanion", description="Scrap Xanion that can be refined into Xanion.", icon="data/textures/icons/scrap-metal.png", mesh="", price=13, size=0.04, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,scrap=true,xanion=true}, chains={}, }
goods["Semi Conductor"] = {name="Semi Conductor", plural="Semi Conductors", description="Used for building microchips and other sorts of electric things.", icon="data/textures/icons/semi-conductor.png", mesh="data/meshes/trading-goods/crate-06.obj", price=129, size=0.1, level=4, importance=5, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Servo"] = {name="Servo", plural="Servos", description="Little multi-purpose machines that can be used in moving parts.", icon="data/textures/icons/servo.png", mesh="data/meshes/trading-goods/crate-04.obj", price=1387, size=0.25, level=5, importance=3, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,technology=true}, }
goods["Sheep"] = {name="Sheep", plural="Sheep", description="Sheep.", icon="data/textures/icons/sheep.png", mesh="data/meshes/trading-goods/crate-food.obj", price=130, size=1, level=2, importance=1, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true,technology=true}, }
goods["Silicon"] = {name="Silicon", plural="Silicon", description="A box with shards of silicon.", icon="data/textures/icons/silicium.png", mesh="data/meshes/trading-goods/silicon.obj", price=500, size=1, level=0, importance=3, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Silver"] = {name="Silver", plural="Silver", description="A small box containing silver bars.", icon="data/textures/icons/metal-bar.png", mesh="", price=300, size=0.5, level=0, importance=3, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Slave"] = {name="Slave", plural="Slaves", description="An unfree life form forced to work for almost no food.", icon="data/textures/icons/slave.png", mesh="data/meshes/trading-goods/crate-01.obj", price=15000, size=1, level=nil, importance=0, illegal=true, dangerous=false, tags={}, chains={}, }
goods["Solar Cell"] = {name="Solar Cell", plural="Solar Cells", description="Electric cells for generating energy from sunlight.", icon="data/textures/icons/solar-cell.png", mesh="data/meshes/trading-goods/solar-cell.obj", price=469, size=2, level=1, importance=1, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Solar Panel"] = {name="Solar Panel", plural="Solar Panels", description="Solar panels that can generate electricity from sunlight.", icon="data/textures/icons/satellite.png", mesh="data/meshes/trading-goods/solarpanel.obj", price=6858, size=6, level=5, importance=1, illegal=false, dangerous=false, tags={technology=true}, chains={technology=true}, }
goods["Solvent"] = {name="Solvent", plural="Solvent", description="A tank filled with a common industrial solvent, found all over the galaxy.", icon="data/textures/icons/solvent.png", mesh="data/meshes/trading-goods/adhesive-solvent.obj", price=402, size=1, level=3, importance=2, illegal=false, dangerous=false, tags={industrial=true}, chains={consumer=true,industrial=true,military=true}, }
goods["Spices"] = {name="Spices", plural="Spices", description="A box with various little bags of spices.", icon="data/textures/icons/spices.png", mesh="data/meshes/trading-goods/crate-08.obj", price=268, size=0.3, level=5, importance=1, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Steel"] = {name="Steel", plural="Steel", description="Raw steel.", icon="data/textures/icons/i-beam.png", mesh="", price=277, size=1, level=1, importance=22, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true,technology=true}, }
goods["Steel Tube"] = {name="Steel Tube", plural="Steel Tubes", description="Long multi-purpose steel tubes.", icon="data/textures/icons/steel-tube.png", mesh="data/meshes/trading-goods/steel-tube.obj", price=704, size=3, level=4, importance=3, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true,military=true,technology=true}, }
goods["Targeting Card"] = {name="Targeting Card", plural="Targeting Cards", description="Multi-purpose chip with targeting software for missiles or turrets.", icon="data/textures/icons/targeting-card.png", mesh="data/meshes/trading-goods/crate-06.obj", price=11873, size=0.5, level=6, importance=1, illegal=false, dangerous=false, tags={military=true}, chains={military=true}, }
goods["Targeting System"] = {name="Targeting System", plural="Targeting Systems", description="Computer system that is able to track multiple targets.", icon="data/textures/icons/targeting-system.png", mesh="data/meshes/trading-goods/crate-06.obj", price=29674, size=0.75, level=8, importance=0, illegal=false, dangerous=false, tags={military=true}, chains={military=true}, }
goods["Tea"] = {name="Tea", plural="Tea", description="A bag of various dried teas.", icon="data/textures/icons/tea.png", mesh="data/meshes/trading-goods/crate-08.obj", price=37, size=0.2, level=1, importance=0, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Teleporter"] = {name="Teleporter", plural="Teleporters", description="Short range one-man hyperspace teleporters.", icon="data/textures/icons/teleport.png", mesh="data/meshes/trading-goods/crate-01.obj", price=39365, size=12, level=8, importance=3, illegal=false, dangerous=false, tags={technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Titanium Ore"] = {name="Titanium Ore", plural="Titanium Ore", description="Titanium ore that can be refined into Titanium.", icon="data/textures/icons/rock.png", mesh="", price=3, size=0.025, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,ore=true,titanium=true}, chains={}, }
goods["Tools"] = {name="Tools", plural="Tools", description="A set of tools used by mechanics.", icon="data/textures/icons/tools.png", mesh="data/meshes/trading-goods/crate-tools.obj", price=214, size=0.4, level=4, importance=0, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,technology=true}, }
goods["Toxic Waste"] = {name="Toxic Waste", plural="Toxic Waste", description="A tank full of some glowing liquid. Highly toxic.", icon="data/textures/icons/toxic-waste.png", mesh="data/meshes/trading-goods/toxic-waste.obj", price=15, size=4, level=nil, importance=0, illegal=false, dangerous=true, tags={basic=true}, chains={}, }
goods["Transformator"] = {name="Transformator", plural="Transformators", description="A small item for transforming all kinds of energy.", icon="data/textures/icons/grenade.png", mesh="data/meshes/trading-goods/crate-04.obj", price=209, size=0.2, level=4, importance=11, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Trinium Ore"] = {name="Trinium Ore", plural="Trinium Ore", description="Trinium ore that can be refined into Trinium.", icon="data/textures/icons/rock.png", mesh="", price=5, size=0.025, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,ore=true,trinium=true}, chains={}, }
goods["Turbine"] = {name="Turbine", plural="Turbines", description="Multi-purpose turbine.", icon="data/textures/icons/turbine.png", mesh="data/meshes/trading-goods/accelerator.obj", price=16729, size=7.5, level=6, importance=1, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,technology=true}, }
goods["Vegetable"] = {name="Vegetable", plural="Vegetables", description="A container with different sorts of vegetables.", icon="data/textures/icons/vegetables.png", mesh="data/meshes/trading-goods/crate-09.obj", price=32, size=1, level=1, importance=1, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Vehicle"] = {name="Vehicle", plural="Vehicles", description="A vehicle used for planetary exploration missions.", icon="data/textures/icons/apc.png", mesh="data/meshes/trading-goods/crate-01.obj", price=77087, size=25, level=8, importance=0, illegal=false, dangerous=false, tags={industrial=true}, chains={industrial=true}, }
goods["War Robot"] = {name="War Robot", plural="War Robots", description="A big robot that is highly armed and very deadly.", icon="data/textures/icons/missile-mech.png", mesh="data/meshes/trading-goods/crate-01.obj", price=92186, size=8, level=9, importance=0, illegal=false, dangerous=true, tags={military=true}, chains={military=true}, }
goods["Warhead"] = {name="Warhead", plural="Warheads", description="Explosive heads for rockets.", icon="data/textures/icons/warhead.png", mesh="data/meshes/trading-goods/crate-06.obj", price=5630, size=3, level=5, importance=1, illegal=false, dangerous=true, tags={military=true}, chains={military=true}, }
goods["Water"] = {name="Water", plural="Water", description="A tank full of clear water.", icon="data/textures/icons/water.png", mesh="data/meshes/trading-goods/crate-liquids.obj", price=20, size=0.35, level=0, importance=24, illegal=false, dangerous=false, tags={consumer=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Wheat"] = {name="Wheat", plural="Wheat", description="A container full of wheat.", icon="data/textures/icons/wheat.png", mesh="data/meshes/trading-goods/crate-09.obj", price=23, size=1, level=1, importance=9, illegal=false, dangerous=false, tags={consumer=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
goods["Wine"] = {name="Wine", plural="Wine", description="A box of wine.", icon="data/textures/icons/wine-glass.png", mesh="data/meshes/trading-goods/crate-food.obj", price=182, size=0.5, level=4, importance=1, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Wire"] = {name="Wire", plural="Wires", description="Around 100 meters of thin wire.", icon="data/textures/icons/wire.png", mesh="data/meshes/trading-goods/crate-04.obj", price=95, size=0.5, level=4, importance=6, illegal=false, dangerous=false, tags={industrial=true,technology=true}, chains={industrial=true,military=true,technology=true}, }
goods["Wood"] = {name="Wood", plural="Wood", description="A big block of compressed wood.", icon="data/textures/icons/log.png", mesh="data/meshes/trading-goods/crate-09.obj", price=350, size=2.5, level=1, importance=1, illegal=false, dangerous=false, tags={consumer=true}, chains={consumer=true}, }
goods["Xanion Ore"] = {name="Xanion Ore", plural="Xanion Ore", description="Xanion ore that can be refined into Xanion.", icon="data/textures/icons/rock.png", mesh="", price=7, size=0.025, level=nil, importance=0, illegal=false, dangerous=false, tags={basic=true,ore=true,xanion=true}, chains={}, }
goods["Zinc"] = {name="Zinc", plural="Zinc", description="A medium sized crate filled with zinc fragments.", icon="data/textures/icons/zinc.png", mesh="", price=250, size=1, level=0, importance=3, illegal=false, dangerous=false, tags={basic=true}, chains={basic=true,consumer=true,industrial=true,military=true,technology=true}, }
